name: 'Latest Flutter Version Action'
description: 'Outputs information about the latest Flutter version in a channel.'
author: 'Scott Hyndman'
inputs:
  channel:
    description: 'The Flutter build release channel'
    required: false
    default: 'stable'
outputs:
  version:
    description: 'The Flutter version's version string (no v prefix)'
runs:
  using: 'node12'
  main: 'dist/index.js'
